export const listaCursos: string[] = [
  "Administração",
  "Ciência da Computação",
  "Ciências Contábeis",
  "Ciências Exatas",
  "Design",
  "Direito",
  "Educação Física",
  "Medicina",
  "Enfermagem",
  "Engenharia Ambiental",
  "Engenharia Civil",
  "Engenharia Computacional",
  "Engenharia de Produção",
  "Engenharia Elétrica",
  "Engenharia Mecânica",
  "Estatística",
];
